services:
  front-end:
    container_name: front-end
    image: ghcr.io/arljohnston/go-microservice-front:latest
    ports:
      - "8000:3000"
    environment:
      GRPC_TARGET: client:50051
    networks:
      - front-end
    depends_on:
      - client

  client:
    container_name: client
    image: ghcr.io/arljohnston/go-microservice-server:latest
    ports:
      - "50051:50051"
      - "2121:2121"
    environment:
      DATABASE_ADDRESS: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: album
    networks:
      - front-end
      - back-end
    depends_on:
      - db

  db:
    container_name: pgsql
    image: postgres:14.15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: album
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "unless-stopped"
    networks:
      - back-end

networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge
