services:
  front-end:
    image: ghcr.io/arljohnston/go-microservice-front:latest
    ports:
      - 8000:3000
    environment:
      GRPC_TARGET: client:50051
    depends_on:
      - client
    networks:
      - host
      - internal

  client:
    image: ghcr.io/arljohnston/go-microservice-server:latest
    ports:
      - 50051:50051
      - 2121:2121
    environment:
      DATABASE_ADDRESS: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: album
    depends_on:
      - db
    networks:
      - host
      - internal

  db:
    image: postgres:14-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: album
    configs:
      - source: db_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - host
      - internal

networks:
  host:
    name: host
    external: true
  internal:
    driver: overlay


configs:
  db_init_sql:
    file: ./create-tables.sql
