version: '3'
services:
  hello-world:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - app:/cmd

  go-auto:
    image: otel/autoinstrumentation-go
    privileged: true
    pid: "host"
    depends_on:
      - hello-world
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
      - OTEL_GO_AUTO_TARGET_EXE=/hello-world
      - OTEL_SERVICE_NAME=hello-world
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      # - app:/cmd
      - /proc:/host/proc

volumes:
  app:
