services:
  main:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - app:/cmd
    - data:/data

  go-auto:
    image: otel/autoinstrumentation-go
    privileged: true
    pid: "host"
    depends_on:
      - main
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
      - OTEL_GO_AUTO_TARGET_EXE=/main
      - OTEL_SERVICE_NAME=main
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      - /proc:/host/proc
      - data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof
      - 4318:4318 # http
      - 13133:13133 # health_check
      - 55679:55679 #zpages

volumes:
  app:
  data:
