services:
  main:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - app:/cmd
    - data:/data

  go-auto:
    image: otel/autoinstrumentation-go
    privileged: true
    pid: "host"
    depends_on:
      - main
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
      - OTEL_GO_AUTO_TARGET_EXE=/main
      - OTEL_SERVICE_NAME=main
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      # - app:/cmd
      - /proc:/host/proc

volumes:
  app:
  data:
