apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: front-end-ns
  labels:
    role: front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      role: front
  template:
    metadata:
      labels:
        role: front
    spec:
      containers:
      - name: front-end
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
