global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ "localhost:9002" ]

  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: [ "localhost:8080" ]
