# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: album.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'album.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lbum.proto\x12\x05\x61lbum\"P\n\x05\x41lbum\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x03\x12\r\n\x05\x63over\x18\x05 \x01(\t\"\x18\n\nIdentifier\x12\n\n\x02id\x18\x01 \x01(\x03\"\x16\n\x05Score\x12\r\n\x05score\x18\x01 \x01(\x03\"O\n\rUpdateRequest\x12\x1e\n\x08oldAlbum\x18\x01 \x01(\x0b\x32\x0c.album.Album\x12\x1e\n\x08newAlbum\x18\x02 \x01(\x0b\x32\x0c.album.Album\"\x05\n\x03Nil2\x8f\x02\n\x06\x41lbums\x12+\n\x06\x43reate\x12\x0c.album.Album\x1a\x11.album.Identifier\"\x00\x12$\n\x04Read\x12\n.album.Nil\x1a\x0c.album.Album\"\x00\x30\x01\x12,\n\x06Update\x12\x14.album.UpdateRequest\x1a\n.album.Nil\"\x00\x12$\n\x06\x44\x65lete\x12\x0c.album.Album\x1a\n.album.Nil\"\x00\x12.\n\tIncrement\x12\x11.album.Identifier\x1a\x0c.album.Score\"\x00\x12.\n\tDecrement\x12\x11.album.Identifier\x1a\x0c.album.Score\"\x00\x42&Z$github.com/ARLJohnston/go-http/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'album_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/ARLJohnston/go-http/proto'
  _globals['_ALBUM']._serialized_start=22
  _globals['_ALBUM']._serialized_end=102
  _globals['_IDENTIFIER']._serialized_start=104
  _globals['_IDENTIFIER']._serialized_end=128
  _globals['_SCORE']._serialized_start=130
  _globals['_SCORE']._serialized_end=152
  _globals['_UPDATEREQUEST']._serialized_start=154
  _globals['_UPDATEREQUEST']._serialized_end=233
  _globals['_NIL']._serialized_start=235
  _globals['_NIL']._serialized_end=240
  _globals['_ALBUMS']._serialized_start=243
  _globals['_ALBUMS']._serialized_end=514
# @@protoc_insertion_point(module_scope)
