name: "Docker build and push to GHCR"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Build and Push Front"
        run: |
          docker login --username ARLJohnston --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build --platform linux/amd64,linux/aarch64 ./front/ --tag ghcr.io/arljohnston/go-microservice-front:latest
          docker push ghcr.io/arljohnston/go-microservice-front:latest

      - name: "Build and Push Server"
        run: |
          docker login --username ARLJohnston --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build --platform linux/amd64,linux/aarch64 ./server/ --tag ghcr.io/arljohnston/go-microservice-server:latest
          docker push ghcr.io/arljohnston/go-microservice-server:latest
