name: "Docker build and push to GHCR"

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: "Build and publish"
        uses: macbre/push-to-ghcr@master
        with:
          image_name: hello-world-ghcr
          github_token: ${{ secrets.GHCR_PAT }}
