name: "Test"

on:
  ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: "Check out code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: "Set up Go"
      uses: actions/setup-go@v5

    - name: "Install Templ"
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: "Generate Templ files"
      working-directory: ./front
      run: templ generate

    - name: "Run front end tests"
      run: go test -race -coverprofile=front.txt -covermode atomic ./front

    - name: "Upload coverage reports to Codecov"
      uses: codecov/codecov-action@v5
      with:
        files: ./front.txt
        flags: front-end
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: "Run server tests"
      run: go test -race -coverprofile=server.txt -covermode atomic ./server

    - name: "Upload coverage reports to Codecov"
      uses: codecov/codecov-action@v5
      with:
        files: ./server.txt
        flags: server
        token: ${{ secrets.CODECOV_TOKEN }}
