name: "Test"

on:
  ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: "Check out code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: "Set up Go"
      uses: actions/setup-go@v5

    - name: "Install Templ"
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: "Generate Templ files"
      working-directory: ./front
      run: templ generate

    - name: "Run tests"
      run: go test -race -coverprofile=coverage.txt -covermode atomic ./server ./front

    - name: "Upload coverage reports to Codecov"
      uses: codecov/codecov-action@v4.0.1
      with:
        files: ./coverage.txt
        token: ${{ secrets.CODECOV_TOKEN }}
