name: "Validate"

on:
  push:
    paths-ignore:
      - '*/*.md'
  pull_request:
    paths-ignore:
      - '*/*.md'

jobs:
  kubeval:
    runs-on: ubuntu-22.04
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Validate"
        uses: instrumenta/kubeval-action@master
        with:
          path: deployments/kompose
